version: '3.8'

services:
  postgres:
    container_name: nestapi-pg
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nestapi-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres